CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
)

CREATE TABLE IF NOT EXISTS books(
    id SERIAL PRIMARY KEY,
    name VARCHAR (100) NOT NULL UNIQUE
)